---
- name: Ensure packages dependencies
  become: yes
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - iptables
    - iptables-persistent

- name: Setup ipv4 forwarding
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: '{{ bastion_firewall_ipv4_forwarding }}'
    reload: yes
    state: present
    sysctl_file: /etc/sysctl.d/90-ipv4-forwarding.conf

- name: Compile ipv4 iptables rules
  become: yes
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.bastion.v4
    mode: 0400
    owner: root

- name: Apply ipv4 rules
  become: yes
  changed_when: false
  shell: iptables-restore < /etc/iptables/rules.bastion.v4

- name: Save iptables rules
  become: yes
  command: netfilter-persistent save
  register: save_result
  changed_when: 'save_result.rc != 0'
